### ISSUE TITLE
Security/escaping issue

### ISSUE THREAD

**Issue by petenelson** [petenelson/wp-rest-api-log#123]
Concerning: https://wordpress.org/support/topic/security-issue-76/

If malformed input is sent to the REST interface, then the plugin doesn't escape it properly when displaying it in the admin area. It's possible to inject HTML tags. I am not sure how far it can be taken, because I haven't read the code to see exactly what it's doing. But this, for example, if you view it in your plugin, applies some of the markup:

`curl -S -d 'test=not bold<strong>bold</strong>' https://example.com/wp-json/something/`

**Comment by JudeRosario** [comment]
Hi Pete

I work for David who initially contacted you about this issue on .org. I am attaching some info here to help with the debug process. I can confirm the issue is present on the `fix/escaping-issues` branch tested up to commit `c7e39a1`

This is what the plugin presently captures and stores in the DB. 

```
{"user_email":"jjj@kkk.ccc","public_key":"-----BEGIN PUBLIC KEY-----nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuEp9PJWcBkIFpye5VJponku3eRg9llOgeI+gczCNS9xazAFnCv9NxDr4OX1woyqMRsaKUNA46+zWhCXC6Nd+hntML11lt45iJdUQZLTfQs10zGXueZtENs6B59SeKxCT3nTHEi7Y1kNp//Coh6o5jJnWvRwGg1TB+7eexqUxudubclOF8F0bk/h4UeLPLY3sFV2MdxPo93p5O0Apxmdu6OhnhYO6DVfIraBRihuCAt4aE6sO8oct23MyHBgTBRsN3n2/jRGAQ3ukr+HzlfifMsUMnGTWri5ut61FcSgV6/A6OToE5rGO1Ot+eOZJJkZ3jaOHSHiVNubnxQ7VOZPNMcLitnwQIDAQABn-----END PUBLIC KEY-----n","signature_algorithm":"sha256","signature_hash":"FoHETqWOB4qAq9EPqr2r0w9Mjynx0ZqEkGW0MO2z37DJqD5SQUSem/hSibCMWRQRc8kp4xJxh9NonOVTpzawg5XVCdX+5vK9lgRoo1nZadBgyaa0QATJrBVUSR5vz+/jhQAGLj4TnaMCBgMXm8bZWjEDMnQ5eX060lBj9riTpI7Ewr7rA3AoZPsELfw0c1okGymJnHPUcny5XlgeTBWdVur3bNVfa8T3w3jR5BnFzO3hlqfyHMVR77p7BdZr6Avw8Nwajs0hlJA5pEyp5hvp7XqajoR1I6gvoTRYpaCr5XBSqDS2Q2fn9HY9lcChEpBsKihnu8FYAQahUPiyHG+k7DZUeQ=="}
```

This is what Android sends it via the POST request

```
{"user_email":"jjj@kkk.ccc","public_key":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuEp9PJWcBkIFpye5VJpo\nku3eRg9llOgeI+gczCNS9xazAFnCv9NxDr4OX1woyqMRsaKUNA46+zWhCXC6Nd+h\ntML11lt45iJdUQZLTfQs10zGXueZtENs6B59SeKxCT3nTHEi7Y1kNp\/\/Coh6o5jJ\nWvRwGg1TB+7eexqUxudubclOF8F0bk\/h4UeLPLY3sFV2MdxPo93p5O0Apxmdu6Oh\nhYO6DVfIraBRihuCAt4aE6sO8oct23MyHBgTBRsN3n2\/jRGAQ3ukr+HzlfifMsUM\nGTWri5ut61FcSgV6\/A6OToE5rGO1Ot+eOZJJkZ3jaOHSHiVNubnxQ7VOZPNMcLit\nwQIDAQAB\n-----END PUBLIC KEY-----\n","signature_algorithm":"sha256","signature_hash":"FoHETqWOB4qAq9EPqr2r0w9Mjynx0ZqEkGW0MO2z37DJqD5SQUSem\/hSibCMWRQRc8kp4xJxh9No\nOVTpzawg5XVCdX+5vK9lgRoo1nZadBgyaa0QATJrBVUSR5vz+\/jhQAGLj4TnaMCBgMXm8bZWjEDM\nQ5eX060lBj9riTpI7Ewr7rA3AoZPsELfw0c1okGymJnHPUcny5XlgeTBWdVur3bNVfa8T3w3jR5B\nFzO3hlqfyHMVR77p7BdZr6Avw8Nwajs0hlJA5pEyp5hvp7XqajoR1I6gvoTRYpaCr5XBSqDS2Q2f\n9HY9lcChEpBsKihnu8FYAQahUPiyHG+k7DZUeQ=="}
```

Notice how the new line sequences lose the escape character `\`. Let me know if you need further help in testing or debugging this.

**Comment by petenelson** [comment]
Hmmm, that last commit should have taken care of the \n issue, but I'll take a look at it.  Thank you for providing the POST payload, will help with debugging.

**Comment by petenelson** [comment]
@JudeRosario pushed up another commit which addresses the request body, let me know if that takes care of it.

**Comment by JudeRosario** [comment]
Hi again @petenelson ,  Sorry about the delay in response Looks like this has fixed it. Thanks for the great plugin !
