### ISSUE TITLE
Can we log wp_remote_get and wp_remote_post with this plugin? how to extend for this purpose?

### ISSUE THREAD

**Issue by SaeedSoltoon** [petenelson/wp-rest-api-log#132]
hi thank you for this great plugin.
Can we log `wp_remote_get` and `wp_remote_post` with this plugin?
I have some routes for user registration in my wp app that i have to call some services with `wp_remote_get` and `wp_remote_post` in registration rest route , is there any way to log requests and responses with this plugin?
i already add these filters
`
add_filter( 'http_request_args', array( __CLASS__, 'filter_http_request_args' ), 99, 2 );
add_filter( 'pre_http_request',  array( __CLASS__, 'filter_pre_http_request' ), 99, 3 );
add_action( 'http_api_debug',    array( __CLASS__, 'action_http_api_debug' ), 99, 5 );
`
to `class-wp-rest-api-log.php` in `plugins_loaded` method, but i dont know how to save it into database tables to view the logs from admin area.

Thank you for answering.

**Comment by petenelson** [comment]
That's something I've been considering adding as one of my work projects communicates with an external API frequently and I log those requests/responses using my plugin. It's not automatic though and eventually I would like to add such functionality.

In the meantime, you can do it manually by running:
`do_action( WP_REST_API_Log_Common::PLUGIN_NAME . '-insert', $args );`
inside your own theme or plugin to 

Check https://github.com/petenelson/wp-rest-api-log/blob/develop/includes/class-wp-rest-api-log.php#L91 and https://github.com/petenelson/wp-rest-api-log/blob/develop/includes/class-wp-rest-api-log-elasticpress.php#L119 for some code examples.

I would not recommend editing this plugin's code to add such functionality as future release will overwrite your changes.
