### ISSUE TITLE
Filter by Method

### ISSUE THREAD

**Issue by jnz31** [petenelson/wp-rest-api-log#144]
hi

thanks for this tool. but the filter method seems to be broken? filtering by method doesn't change a thing, the list still shows all requests..
any clue on what could be wrong here?

**Comment by benhuson** [comment]
Filtering by status also does not work.

**Comment by petenelson** [comment]
Fixed in #158

**Comment by minhlam3118410220** [comment]
Currently, when searching by method, title, status, it works. But I don't know how to search by User
