### ISSUE TITLE
How to clean logs manually?

### ISSUE THREAD

**Issue by gdelacc** [petenelson/wp-rest-api-log#160]
Is there any way to clean the DB manually by SQL query or simmilar?

I've detected in my WP installation that the tables `wp_rest_api_log` and `wp_rest_api_logmeta` does not exist and in `wp_postmeta` the plugin inserted items in meta_key like:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/6078315/236458709-0fc99ed0-1cb2-4191-8170-4c8b6089d818.png">

The function of purge_all_entries hanged about 5 mins in spite of icrease php max_execution_time to 3660 in my server.

**Comment by petenelson** [comment]
These two SQL commands should bulk delete the database REST API log records. You may need to adjust the table names to match your installation.

```
delete from wp_postmeta where post_id in ( select ID from wp_posts where post_type = 'wp-rest-api-log' );
delete from wp_posts where post_type = 'wp-rest-api-log';
```

**Comment by gdelacc** [comment]
> These two SQL commands should bulk delete the database REST API log records. You may need to adjust the table names to match your installation.
> 
> ```
> delete from wp_postmeta where post_id in ( select ID from wp_posts where post_type = 'wp-rest-api-log' );
> delete from wp_posts where post_type = 'wp-rest-api-log';
> ```

Thanks!
