### ISSUE TITLE
No headers visible

### ISSUE THREAD

**Issue by enricodeleo** [petenelson/wp-rest-api-log#54]
Hi!
I just started using this plugin and everything seems to work fine but I can't see any headers information within logs. Is there something I'm missing?

**Comment by petenelson** [comment]
It's collapsed by default and clicking it should expand it.  If you still don't see headers, let me know and I'll take a look.

**Comment by enricodeleo** [comment]
@petenelson thank you for your kind reply. Yes, they are collapsed but also empty (screenshot below).

![image](https://cloud.githubusercontent.com/assets/3534555/11849665/43d7a4ae-a429-11e5-8ae6-cf910fb36479.png)

The same happens for query and body parameters.

Any idea?

**Comment by petenelson** [comment]
Could be because of the newer version of the REST API that is now in core.  I started on a major rewrite of this plugin several months ago, so this is a good incentive to get it finished and working correctly with the current REST API version.

**Comment by enricodeleo** [comment]
@petenelson thank you for your reply. Yes, maybe. I'll keep watching this project and hopefully contribute :)
